Made names on cards clickable issue#10
justsanchez/FESonline.github.io pull request #16
Opened 2024-07-03 00:44 UTC by Jovani-JRH7

### Description

Please include a summary of the changes and the related issue. 

Add issue number at the end
Issue: https://github.com/justsanchez/FESonline.github.io/issues/

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2024-07-03 00:54 UTC, justsanchez requested changes

2024-07-03 00:54 UTC, justsanchez commented on team.html
> +                </a>
The `<a>` tags should only surround the name not the role

2024-07-03 00:54 UTC, justsanchez commented on team.html
> +                </a>
same here

2024-07-03 00:54 UTC, justsanchez commented on team.html
> +                </a>
same here

2024-07-03 00:54 UTC, justsanchez commented on team.html
> +                </a>
same here

2024-07-03 00:54 UTC, justsanchez commented on team.html
> +                </a>
same here

2024-07-03 00:54 UTC, justsanchez commented on team.html
> +                </a>
same here

2024-07-03 00:55 UTC, justsanchez commented
Also fill out the Pull Request info for every PR

2024-07-03 01:09 UTC, Jovani-JRH7 commented
Sorry about that, I'm used to pressing CTRL + Enter to jump to the next line. When I tried doing that when creating the pull request it would just submit it instead of jumping to the next line.
Won't happen again, I'll fill out the pull request info next time.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: justsanchez ***@***.***>
Sent: Tuesday, July 2, 2024 8:55:48 PM
To: justsanchez/FESonline.github.io ***@***.***>
Cc: Rivera-hernandez, Jovani ***@***.***>; State change ***@***.***>
Subject: Re: [justsanchez/FESonline.github.io] Made names on cards clickable issue#10 (PR #16)


[This email originated from outside of UNCW]

Also fill out the Pull Request info for every PR

—
Reply to this email directly, view it on GitHub<https://github.com/justsanchez/FESonline.github.io/pull/16#issuecomment-2204803199>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BHXRQ4DEOOGPHDQXFYPY2FTZKNDZJAVCNFSM6AAAAABKIQ7EZ2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMBUHAYDGMJZHE>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2024-07-09 22:25 UTC, Jovani-JRH7 commented
Have fixed errors.

2024-07-10 17:27 UTC, justsanchez approved these changes

2024-07-17 00:07 UTC, merged